name: sync-fork
on:
  schedule:
    - cron: '0/30 * * * *'
  workflow_dispatch: { }
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git config --global user.name 'bjon'
          git config --global user.email 'bjon@users.noreply.github.com'
          git remote add upstream https://github.com/ValveSoftware/counter-strike_regional_standings.git
          git fetch upstream
          git checkout
          git merge --no-edit upstream/main
          git push
