name: sync-fork
on:
  schedule:
    - cron: '0/30 * * * *'
  workflow_dispatch: { }
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - run: gh repo sync ValveSoftware/counter-strike_regional_standings --branch main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}